# Generated by Django 5.0.6 on 2024-05-15 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_orders', '0003_rename_movies_order_movieorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieorder',
            name='purchased_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
