# Generated by Django 5.0.6 on 2024-05-14 22:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
        ('movies_orders', '0002_movies_order_delete_movies_orders'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='orders',
            field=models.ManyToManyField(related_name='movies_ordered', through='movies_orders.Movies_order', to=settings.AUTH_USER_MODEL),
        ),
    ]
